import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cn from 'classnames'


import { Navbar } from "@/components/navbar/Navbar";
import { Providers } from "@/app/store/provider";
import { PersistGates} from "@/app/store/PersistGate";
import context from "react-redux/src/components/Context";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'post',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

        return (
            <html lang="en">
                <body
                    className={cn(
                        "h-screen",
                        "relative bg-[url(/image/firesunset.jpg)]",
                        "bg-no-repeat bg-center bg-fixed bg-cover"
                    )}
                >
                <Providers>
                    <PersistGates>
                        <Navbar />
                        {children}
                    </PersistGates>
                </Providers>
                </body>
            </html>
        )
    // }
}
